#!/usr/bin/env bash
TEMP=/tmp/current_wall

files=(~/Library/images/Wallpapers/*)

index=$(cat $TEMP)
index=$((index+1))
if [ $index -ge ${#files[@]} ]; then
  index=0
fi
echo $index > $TEMP
swww img "${files[$index]}" --transition-duration 2 --transition-type center --transition-fps 60

exit 0
